import pyautogui as pt
from spktakecmd import speak
from time import sleep

def howto():
    print("I'm showing how to save a note in notepad.")
    speak("I am showing how to save a note in notepad.")
    sleep(0.3)
    print("Firtst press Window key/go to window.")
    speak("First press Window key")
    pt.press('win')
    print("Then type in search Bar Notepad")
    speak("Then type in Seacrh Bar, Notepad")
    pt.typewrite('notepad',0.3)
    print("Press Enter")
    speak("Press Enter")
    pt.press('enter')
    sleep(0.5)
    print("Now you have a Notepad Window.")
    speak("Now you have a Notepad Window")
    sleep(0.2)
    print("Type your message")
    speak("Type your message")
    speak("Suppose I am write, How to save a Notpad Message?")
    pt.typewrite("How to save a Notpad Message?",0.3)
    speak("Go to Left Cornor File,")
    sleep(0.5)
    pt.press('f10')
    sleep(0.2)
    pt.press('f')
    speak("Find Save, and press Enter")
    sleep(0.3)
    pt.press('s')
    speak("Now you can Choose you folder, and rename it.")
    speak("I am going to rename it, howtonotepad.txt")
    pt.typewrite('howtonotepad.txt',0.3)
    print("Press Enter")
    speak("Press Enter")
    pt.press('enter')
    print("Now your Note has been successfully Saved")
    speak("Now your Note has been successfully Saved")
    sleep(0.3)
    pt.hotkey('alt','space')
    sleep(0.1)
    pt.press('c')

# howto()